### ISSUE TITLE
Fatal error: Uncaught TypeError: Typed property

### ISSUE THREAD

**Issue by shahmanthan1209** [reload/github-security-jira#165]
Fatal error: Uncaught TypeError: Typed property GitHubSecurityJira\SecurityAlertIssue::$safeVersion must be string, null used in /opt/ghsec-jira/src/SecurityAlertIssue.php:41
Stack trace:
#0 /opt/ghsec-jira/src/SyncCommand.php(94): GitHubSecurityJira\SecurityAlertIssue->__construct(Array)
#1 /opt/ghsec-jira/vendor/symfony/console/Command/Command.php(256): GitHubSecurityJira\SyncCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /opt/ghsec-jira/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /opt/ghsec-jira/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(GitHubSecurityJira\SyncCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /opt/ghsec-jira/vendor/symfony/console/Applicati in /opt/ghsec-jira/src/SecurityAlertIssue.php on line 41

Team, can you guide me here?

**Comment by arnested** [comment]
Please check if you're using the latest version. This sounds very much like what we fixed in #85.

**Comment by shahmanthan1209** [comment]
Thanks!
