### ISSUE TITLE
wrong alerts getting sent to Jira

### ISSUE THREAD

**Issue by codebop** [reload/github-security-jira#168]
I implemented this tool on a repo of mine. The number of issues created in Jira matches the total number of open security alerts that repo has (Dependabot, secrets scanning and code scanning combined), but all of the issues opened in Jira are Dependabot issues, including a bunch of closed Dependabot issues. This happens using tag v1.2.0

**Comment by abhisheknigam87** [comment]
I am also observing the same issue. Few of the closed dependabot issues are created in JIRA whereas few open dependabot issues are being skipped.

**Comment by arnested** [comment]
I just merged #166. Please try the updated version.

**Comment by codebop** [comment]
@arnested I tried with the v1.3.1 tag and it successfully sent only open Dependabot issues to my Jira board. What about the rest of my security alerts though? Code scanning and secrets scanning alerts don't get sent. Should they? Based on the README I would think so, but maybe this tool is just for Dependabot alerts?

**Comment by arnested** [comment]
> @arnested I tried with the v1.3.1 tag and it successfully sent only open Dependabot issues to my Jira board. What about the rest of my security alerts though? Code scanning and secrets scanning alerts don't get sent. Should they? Based on the README I would think so, but maybe this tool is just for Dependabot alerts?

It was written just for Dependabot alerts (I don't think the other alerts existed back when we created this tool).

**Comment by codebop** [comment]
@arnested Thank you. Understood. I would suggest clarifying that in the README. FYI code and secrets scanning are available for GitHub Advanced Security customers only.

**Comment by arnested** [comment]
Hi @codebop 

I'll add a clarification in #177 

Thank you for the feedback, and please don't hesitate to suggest other improvements.

**Comment by abhisheknigam87** [comment]
Thanks for getting this fixed. 
I have one more query. Does it also check whether the opened dependabot alert is already logged in JIRA ?
My use case is: I have say 5 dependabot alerts. Using this tool, 5 respective JIRAs get logged.
Now 2 new alerts have come up. If I rerun this tool, will it create 2 JIRAs or 7 JIRAs ?

**Comment by arnested** [comment]
@abhisheknigam87 only two new will be created.

Metadata is added to Jira labels and then used to detect previously created issues.
