### ISSUE TITLE
Add link to dependabot alert in GitHub

### ISSUE THREAD

**Issue by HarlemSquirrel** [reload/github-security-jira#210]
It would be very helpful to have a link to the dependabot alert in GitHub added to the Jira issue description.

**Comment by HarlemSquirrel** [comment]
I was playing with the GraphQL explorer and I don't see a way to request the URL. But I found we can request the alert `number` as one of the nodes which should allow constructing the URL like 

```
https://github.com/:org/:repo/security/dependabot/:number
```

**Comment by arnested** [comment]
> I was playing with the GraphQL explorer and I don't see a way to request the URL. But I found we can request the alert `number` as one of the nodes which should allow constructing the URL like
> 
> ```
> https://github.com/:org/:repo/security/dependabot/:number
> ```

Nice :+1:

**Comment by CRUZEAAKASH** [comment]
Can you please elaborate a little, how can I use this above link with reload/github-security-jira github action

**Comment by xendk** [comment]
@CRUZEAAKASH It needs to be implemented in code. @HarlemSquirrel is taking a stab at it in https://github.com/reload/github-security-jira/pull/255.

**Comment by arnested** [comment]
And we just received our first security alerts with the alert link in them. Works as expected. Thanks again, @HarlemSquirrel
