### ISSUE TITLE
JIRA ticket creation fails if your maven module folder has spaces in it

### ISSUE THREAD

**Issue by ManuelCalvo3Pillar** [reload/github-security-jira#231]
If your maven project is a multi module one, and you have module folders with spaces in them, the JIRA ticket creation process will fail. This is because JIRA doesn't allow to create labels that contains spaces. See: https://confluence.atlassian.com/automationkb/automation-for-jira-fails-to-copy-components-list-to-label-with-error-message-the-label-contains-spaces-which-is-invalid-1072473388.html#:~:text=The%20error%20message%20happens%20because,include%20spaces%20in%20their%20names

In our case our pom.xml looked like this:
< modules>
		< module>nice-module</ module>
		< module>Wrong module</ module>

When the GitHub action runs it fails and reports this error:
CURL HTTP Request Failed: Status Code : 400, URL:https://my.atlassian.net/rest/api/2/search
Error Message : {“errorMessages”:[“The label ‘glob-parent:Wrong Module:5.1.2’ can’t contain spaces.“],“warningMessages”:[]}

That is because this action code create labels that are like a "path" pointing to where the dependency with issues is, and part of that "path" is the module name. You can see that in this line:
https://github.com/reload/github-security-jira/blob/d7f59573fb0542de6376279f29defef009aefc2c/src/SecurityAlertIssue.php#L127

The code could remove the spaces to avoid JIRA rejecting the label.

**Comment by shiriuki** [comment]
This seems to be fixed by this pull request:
https://github.com/reload/github-security-jira/pull/233/files/3070e94515e4c49ee96706e513c6545f11aaa5c7

**Comment by xendk** [comment]
Indeed, this is fixed by #233
