### ISSUE TITLE
JIRA ticket creation fails if your module folder has spaces in it, on creation a label

### ISSUE THREAD

**Issue by webhelpadmin** [reload/github-security-jira#289]
Error Message : {"errorMessages":["The label 'Newtonsoft.Json:Clients/GE US  
  /CustomerRelation:13.0.1' can't contain spaces."],"warningMessages":[]}   
![image](https://github.com/reload/github-security-jira/assets/57407537/ba839e00-29ae-40ac-93fc-0978e3708017)

**Comment by xendk** [comment]
Fixed in latest version.
