### ISSUE TITLE
JSON property "parent" must not be NULL

### ISSUE THREAD

**Issue by jmike** [reload/github-security-jira#293]
Github action is breaking since yesterday with the following message...

```
In JsonMapper.php line 229:
                                                                               
  JSON property "parent" in class "JiraRestApi\Issue\IssueField" must not be   
  NULL
```

I assume Jira have changed their API to make `parent` a required field. Any ideas?

**Comment by arnested** [comment]
We are preparing a fix in https://github.com/reload/jira-security-issue/pull/53

Stay tuned.

**Comment by jmike** [comment]
Thank you very much 🙇
