### ISSUE TITLE
Costing for the action

### ISSUE THREAD

**Issue by shahmanthan1209** [reload/github-security-jira#69]
Hi team,
Can you please share the pricing if I use this workflow from the GitHub marketplace?
Regards,
Manthan Shah

**Comment by arnested** [comment]
There is no cost except GitHub bills you for the minutes used running the actions (https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions).

Each run of the action usually takes less than a minute on the repos where we run it our self.

**Comment by shahmanthan1209** [comment]
Thanks for the quick revert.
