### ISSUE TITLE
Adding jira component

### ISSUE THREAD

**Issue by shahmanthan1209** [reload/github-security-jira#72]
Hi team,

I tried adding JIRA_Component in the env section of the workflow code. But during integration, my issues are not getting linked with the newly created component in the JIRA software project. Please advise.

Regards,
Manthan Shah

**Comment by arnested** [comment]
Hi @shahmanthan1209 

Jira components are not supported.

**Comment by shahmanthan1209** [comment]
Thanks for revert!
