### ISSUE TITLE
Populate ticket header with priority

### ISSUE THREAD

**Issue by shahmanthan1209** [reload/github-security-jira#75]
Hi team,
Wondering about populating priority/severity of alerts in the header/title section that have been raised by Dependabot while creating tickets in JIRA software?
Regards,
Manthan Shah

**Comment by shahmanthan1209** [comment]
Hi team,
Can you please advise?

**Comment by arnested** [comment]
Hi @shahmanthan1209 

Are you thinking something along what is mentioned in #60?

**Comment by arnested** [comment]
Due to lack of feedback I'm closing this as a duplicate of #60
